### ISSUE TITLE
整页滚动

### ISSUE THREAD

**Issue by lucyanddarlin** [NameWjp/vue3-scroll-table#1]
作者，请问可以增加整页滚动的效果嘛

**Comment by NameWjp** [comment]
不要表头吗？可以试试css直接隐藏看看

**Comment by lucyanddarlin** [comment]
嗯...就比如一共有 11 条数据，表格一页展示 5 条数据，初始展示第 1-5 条数据，然后滚动之后，展示第 6-10 条，再次滚动，展示第 11 条数据，就类似的效果

**Comment by NameWjp** [comment]
这两天有空我加一下功能来满足你的需求

**Comment by lucyanddarlin** [comment]
感谢感谢！💖

**Comment by NameWjp** [comment]
@lucyanddarlin 加了一个 [scrollCount](https://namewjp.github.io/vue3-scroll-table/?path=/docs/vue3-scroll-table--%E6%BB%9A%E5%8A%A8%E5%A4%9A%E4%B8%AA)，你可以通过调整这个配置来控制恰好滚动一页，0.1.4已经发布。然后“再次滚动，只展示第 11 条数据”，这个我建议在数据末尾插入4条空数据，不知道这样能不能满足你那边的需求

**Comment by lucyanddarlin** [comment]
好滴好滴！有了 `scrollCount` 就可以控制每页展示的条数啦，我只要保证总数据的个数是 `scrollCount` 的倍数就好，确实应该添加若干条空数据，感谢作者~
